version: '3.8'

services:
  app:
    image: api_controle_adocoes:latest
    build: .
    container_name: api_controle_adocoes
    environment:
      - DB_URL=jdbc:postgresql://db:5432/adocoes
      - DB_USER=postgres
      - DB_PASSWORD=postgresql
      - API_SECURITY_TOKEN_SECRET=c0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: controle_adocoes_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: adocoes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: